### ISSUE TITLE
Review rate limiter and ban/unban policy

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicdex-gui-auth#13]
Initially reported by @tonymorony 

Current rate lmits set in configuration:
```
"rate_limiter": {
        "rp_1_min": 400,
        "rp_5_min": 2000,
        "rp_15_min": 10000,
        "rp_30_min": 30000,
        "rp_60_min": 65000
      },
```

Tony had his address banned after ~150 requests in 2 hours total.
I created a new air_dex wallet (all balances are empty), activated a few erc20 assets and got banned in 15 minutes after ~330 requests.

Count done by quick check  on auth_service logs.

Both bans are related to requests with insufficient balances:
```
2022-11-15T12:57:51.207Z INFO  [atomicdex_auth::http] [Ip: 88.246.76.133 | Pubkey: 0xDfb593B78EBd6E1fa1380a50Ce4117Fe7e90CFC1 | Address: /ethereum] Request received.
2022-11-15T12:57:52.149Z WARN  [atomicdex_auth::http] [Ip: 88.246.76.133 | Address: 0xDfb593B78EBd6E1fa1380a50Ce4117Fe7e90CFC1 | Path: /ethereum] Rate exceed, checking balance for 0xDfb593B78EBd6E1fa1380a50Ce4117Fe7e90CFC1 address.
2022-11-15T12:57:52.271Z WARN  [atomicdex_auth::http] [Ip: 88.246.76.133 | Address: 0xDfb593B78EBd6E1fa1380a50Ce4117Fe7e90CFC1 | Path: /ethereum] Wallet 0xDfb593B78EBd6E1fa1380a50Ce4117Fe7e90CFC1 has insufficient balance, returning 406.
```

This does not add up to the limits set in configuration.

**Comment by SirSevenG** [comment]
2nd point:
We've tried to "clear" restrictions by restarting the service, yet it did not help. )
At least for testing purposes, how can we unban an address? @ozkanonur

**Comment by ozkanonur** [comment]
Post Request to '/address-status' with a payload like
```json
[
    {
        "address": String
        "status": Number
    }
    .
    .
    .
]
```

status can be 0, 1 or -1.

-1 means None (In case if you want to let the normal flow work)
0 means Trusted (When you want to bypass everyting)
1 means Blocked (When you want to block the address without checking anything)

Send GET to `/address-status` check the values(if you post any values before).

In order to access that endpoint, you have to be in the same network where gui-auth deployed for security reasons.

**Comment by ozkanonur** [comment]
If 330 requests and 150 requests are per seconds, then that's normal according to your configuration rate limit configuration.

**Comment by ozkanonur** [comment]
> > If 330 requests and 150 requests are per seconds, then that's normal according to your rate limit configuration.
> > ps: I recommend checking gui-auth traffic rather than quicknode. Gui-auth has more traffic income with browser's extra requests. I am not sure if they are count as rate or not, I have to check it.
> 
> It's 150 in 2 hours total(0.02 rq per sec xD) and 330 in 15 minutes total, not per second.

That shouldn't happen. Will check it tomorrow.

**Comment by SirSevenG** [comment]
> Btw, you didn't update the config while the app was running right? Config is loaded at app initialization once. So each config change requires application restart.

A bit late response, still. I've set config a while back and restarted app a few times after already.

**Comment by tonymorony** [comment]
@ozkanonur could you please check it? it's quite a problem atm

**Comment by ozkanonur** [comment]
> @ozkanonur could you please check it? it's quite a problem atm

I did check. Rate counting seems normal. I am thinking maybe if you have enabled too many eth tokens that could reach the limit. If you send 10 request per minute, it becomes 10*active_eth_coins_count requests per minute. I did the update and send a message to @SirSevenG to redeploy auth_service once the pipeline finishes. Please do the exactly same testings once auth_service redeployed and share the results here.

**Comment by SirSevenG** [comment]
@tonymorony We've found an issue with api and potential issues on quicknode proxy, afaik @ozkanonur is working on fixing them atm.

**Comment by ozkanonur** [comment]
Ticker problem is fixed in https://github.com/KomodoPlatform/atomicDEX-API/pull/1550 this PR.

**Comment by SirSevenG** [comment]
Problems on the server side were due to newer redis version, downgraded, auth service works fine now. Much thanks @ozkanonur for help with this one. o7

**Comment by SirSevenG** [comment]
PR is merged, auth service is updated to latest master with new config.
Looks stable so far, thanks @ozkanonur, issue is resolved.
